config/routes.rb
Rails.application.routes.draw do



  #get "todos", to: "todos#index"



  #post "todos", to: "todos#create"



  #get "todos/:id", to: "todos#show"



  get "/home", to: "home#index"



  get "/", to: "home#index"



  resources :todos



  resources :users



  get "/signin" => "sessions#new", as: :new_sessions



  delete "/signout" => "sessions#destroy", as: :destroy_session



  post "/signin" => "sessions#create", as: :sessions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :todo_text, presence: true
  validates :due_date, presence: true
  validates :todo_text, length: { minimum: 2 }

  def to_pleasant_string
    is_completed = completed ? "[X]" : "[ ]"
    "#{id}. #{due_date} #{todo_text} #{is_completed}"
  end

  def self.of_user(user)
    all.where(user_id: user.id)
  end
  def self.completed
    all.where(completed: true)
  end
  def self.not_completed
    all.where(completed: false)
  end
  def self.overdue
    all.where("due_date < ?", Date.today)
  end
  def self.due_today
    all.where("due_date = ?", Date.today)
  end
  def self.due_later
    all.where("due_date > ?", Date.today)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :ensure_user_logged_in



  def ensure_user_logged_in

    unless current_user

      redirect_to "/"

    end

  end



  def current_user



    #memorization



    return @current_user if @current_user



    current_user_id = session[:current_user_id]



    if current_user_id

      @current_user = User.find(current_user_id)

    else

      nil

    end

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    #renders new.html.erb by default
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Invalid credentials! Please try again."
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todo = Todo.of_user(current_user)
    #render plain: Todo.order(:due_date).map { |todo| todo.to_pleasant_string }.join("\n")
    render "index"
  end

  def show
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    #render plain: todo.to_pleasant_string
    render "todo"
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id,
    )
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = Todo.of_user(current_user).find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "users/new"
  end

  def create
    User.create!(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
    )
    redirect_to home_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class= "Home-title"> Welcome to the home page </h1>
<h3 class="Home-authenticate"> If you are a new user sign up <%= link_to "here", new_user_path%> </h3>
<h3 class="Home-authenticate"> If you are already a user sign in <%= link_to "here", new_sessions_path%> </h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Todo Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
        Welcome <%= @current_user.first_name%> !
         <%= link_to "sign-out", destroy_session_path, method: "delete"%>
      </p>
    <% end %>
    <% if flash[:error] %>
     <p class="Flash-error">
      <%= flash[:error] %>
     </p>
    <% end %>
    <%=yield%>
  </body>

</html>

app/views/todos/_todo-section.html.erb
  <section class="TodoSection">
    <div class="TodoSection-head">
      <h2 class="TodoSection-title"> <%= section_title %> </h2>
      <p class="RemainingCount"><%=todos.completed.count%>/<%= todos.count %></p>
    </div>
    <ul class="TodoList">
      <% todos.each do |todo| %>
      <li class="TodoItem">
       <%= form_with(url: "/todos/#{todo.id}", method: "PUT") do%>
        <%= check_box_tag("completed", value= "1",
         checked = todo.completed,
         onclick: "this.form.submit()")
        %>

       <% end %>
        <p class="TodoItem-text" style="text-decoration: <%=render plain: "line-through" if todo.completed%>"> <%=todo.todo_text%> </p>
        <p class="ShowDate"><%= todo.due_date if todo.due_date != Date.today %></p>
        <%= form_with(url: "/todos/#{todo.id}", method: "delete") do%>
         <%= image_submit_tag("delete.png", class: "Delete") %>
        <% end %>
      </li>
    <%end%>
    </ul>
  </section>

app/views/todos/index.html.erb
<main>
  <h1 class="TodoPage-title">My To-do List</h1>
  <%= form_with( url: "/todos", class: "TodoAdd", method: "POST") do %>
    <%= text_field_tag('todo_text',value=nil, placeholder: "What's next?", class: 'TodoText') %>
    <%= date_field_tag('due_date', value=nil, class: "TodoDate") %>
    <%= submit_tag(value="Add", class: "TodoAdd-button") %>
  <% end %>
  <%= render partial: "todo-section", locals: {
    section_title: "Overdue",
    todos: @todo.overdue.not_completed
  } %>
  <%= render partial: "todo-section", locals: {
    section_title: "Due Today",
    todos: @todo.due_today,
  } %>
  <%= render partial: "todo-section", locals: {
    section_title: "Due Later",
    todos: @todo.due_later
  } %>
</main>

app/views/todos/todo.html.erb
<h2>This is a single todo</h2>

app/views/users/new.html.erb
<p class="NewUsers-title"> welcome! </p>
<section class="UsersNew">
<%= form_with url: users_path do |form| %>
 <div class="Form-section">
  <p class="FormInput-label">First name: </p>
  <%= form.text_field :first_name, class: "form-input" %>
 </div>
 <div class="Form-section">
  <p class="FormInput-label">Last name: </p>
  <%= form.text_field :last_name, class: "form-input" %>
 </div>
 <div class="Form-section">
  <p class="FormInput-label">E-mail: </p>
  <%= form.email_field :email, class: "form-input" %>
 </div>
 <div class="Form-section">
  <p class="FormInput-label">Password: </p>
  <%= form.text_field :password, class: "form-input" %>
 </div>
 <div class="Form-section">
  <%= form.submit "Sign-up",class: "Form-submit"%>
 </div>
<% end %>
</section>